/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Control.Control;

/**
 *
 * @author Daar375
 */
public class GameOver extends javax.swing.JFrame {

	/**
	 * Creates new form GameOver
	 */
	
	public GameOver(int pvalue) {
		initComponents();
		PuntosLabel.setText( Integer.toString(pvalue));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		NewRoadB = new javax.swing.JButton();
		ExitB = new javax.swing.JButton();
		GameOverLabel = new javax.swing.JLabel();
		LabelFixedPuntos = new javax.swing.JLabel();
		PuntosLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		NewRoadB.setText("New Road");
		NewRoadB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				NewRoadBActionPerformed(evt);
			}
		});



		ExitB.setText("Exit");
		ExitB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ExitBActionPerformed(evt);
			}
		});

		GameOverLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
		GameOverLabel.setForeground(new java.awt.Color(255, 51, 51));
		GameOverLabel.setText("Game Over");

		LabelFixedPuntos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		LabelFixedPuntos.setText("Points:");

		PuntosLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(GameOverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(147, 147, 147))
				.addGroup(layout.createSequentialGroup().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(NewRoadB)
								.addGap(127, 127, 127).addComponent(NewRoadB).addGap(134, 134, 134).addComponent(ExitB))
						.addGroup(layout.createSequentialGroup().addGap(153, 153, 153).addComponent(LabelFixedPuntos)
								.addGap(18, 18, 18).addComponent(PuntosLabel)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(GameOverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(16, 16, 16)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(LabelFixedPuntos).addComponent(PuntosLabel))
						.addGap(71, 71, 71)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(NewRoadB).addComponent(NewRoadB).addComponent(ExitB))
						.addContainerGap(33, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void NewRoadBActionPerformed(java.awt.event.ActionEvent evt) {
		Control control = new Control();

	}


	private void ExitBActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */


	// Variables declaration - do not modify
	private javax.swing.JButton ExitB;
	private javax.swing.JLabel GameOverLabel;
	private javax.swing.JLabel LabelFixedPuntos;
	private javax.swing.JButton NewRoadB;
	private javax.swing.JLabel PuntosLabel;
	// End of variables declaration
}
